#i18n:config.language.comment
ui.language=ca

#i18n:config.isMetallophone.comment
isMetallophone=true

#i18n:config.midiRange.comment
lowestMidi=36
highestMidi=84

#i18n:config.tipsVisible.comment
tipsVisible=true

#i18n:config.screenSize.comment
screenWidthRatio=0.95
screenHeightRatio=0.8

#i18n:config.nMeasuresCam.comment
nMeasuresCam=4

#i18n:config.nColsQuarter.comment
nColsQuarter=12

#i18n:config.nColsScore.comment
nColsScore=12000

#i18n:config.autoCorrect.comment
autoCorrect=true
