ui.language=ca
# ui.language=ca
autoCorrect=true
tipsVisible=true
showMutted=false
nMeasuresCam=4
nBeatsMeasure=4
nColsBeat=12
nColsScore=12000
dodecaphone=true
screenWidthRatio=0.95
screenHeightRatio=0.8

lastDirectorySvg=G:\\La meva unitat\\Dodecaphenia\\DoDeReBu_v4.0

lastDirectory=G:\\La meva unitat\\Dodecaphenia\\DoDeReBu_v4.0\\SongsInBooklet

